help - Spring
rzonsol/java-portfolio pull request #5
Opened 2016-10-09 14:18 UTC by rzonsol

2016-10-09 15:51 UTC, mszpiler requested changes
Do poprawki

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/Beans.xml
> +        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
Tutaj masz wskazanie na drivera z MySQL, Ty natomiast korzystasz z bazy H2 - zmień na odpowiednią klasę.

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/Beans.xml
> +        <property name="username" value="root"/>
User name i hasło powinno być takie jak skonfigurowałeś podczas inicjalizacji bazy danych przez flyway'a w pom.xml. Username to "sa" Hasło to ""

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/Beans.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Beans.xml - już zwracalem uwagę, że nazwy xmli z małych liter. Druga sprawa - xmle trzymamy w resources w większości przypadków

2016-10-09 15:51 UTC, mszpiler commented on pom.xml
> +                <artifactId>exec-maven-plugin</artifactId>
Spoko narazie może być ten plugin, potem się go przeniesie do modułu małoistotnego jak będziemy przerabiać ten projekt na coś bardziej zaawansowanego

2016-10-09 15:51 UTC, mszpiler commented on pom.xml
> +        <dependency>
Plugin flyway-maven-plugin ma dependency na H2, przenieś to dependency do sekcji dependencies poza ten plugin - w ten sposób biblioteka H2 będzie dostępna w ramach całego projektu, a nie tylko plugina flyway-maven-plugin

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/Student.java
> +    private String Login;
Klasy rozpoczynamy z wielkiej litery, natomiast pola klasy w 99,9% z małej. Zatem do poprawy

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/Student.java
> +    private Integer id;
O a tutaj brak konsekwencji tym razem pole z małej litery.

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/StudentDAO.java
> +    public void setDataSource(DataSource ds);
Interfejs nie powinien robić takich rzeczy jak ustawianie dataSource. Interfejs powinien skupić się na zachowaniach, a tutaj mamy do czynienia z ustawianiem dostępu do zasobów jakimi są dane w bazie danych - zatem metoda do wywalenia

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/StudentJDBCTemplate.java
> +    public void setDataSource(DataSource dataSource) {
Bardziej naturalne będzie inicjalizacja tego beana przez konstruktor

2016-10-09 15:51 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/MainApp.java
> +                new ClassPathXmlApplicationContext("Beans.xml");
Główny plik konfiguracyjny to "spring-module.xml" i ten zawsze powinniśmy ładować

2016-10-09 15:51 UTC, mszpiler commented on src/main/resources/spring-module.xml
> -	<bean id="helloBean" class="org.elearning.portfolio.bean.FirstBean">
Dodałeś nowy plik xml z konfiguracją o nazwie Beans.xml - nie jest on częścią ten naszej głównej konfiguracji ponieważ nie zrobiłeś importu tutaj.
Można sobie rozbijać na więcej niż jeden większą konfigurację dzieląc go na domeny, jednak aby aplikacja w całości działała wszystkie te pliki powinny być zaimportowane w głównym pliku z konfiguracją springa.

2016-10-09 15:51 UTC, mszpiler commented on src/main/resources/spring-module.xml
> +    <bean id="customerDAO" class="org.elearning.portfolio.dao.impl.JdbcCustomerDAO">
Klasa która nie istnieje - do wywalenia ta konfiguracja.

2016-10-09 15:51 UTC, mszpiler commented on src/main/resources/db/migration/V002__addUser.sql
> +insert into USERS ( LOGIN, EMAIL, FIRST_NAME, LAST_NAME) values ('LOGIN1','EMAIL1','NAME1','LASTNAME1');
Powyżej masz plik portfolio-db.mv.db z bazą danych, który znajduje się w pakiecie z javą. 
Po pierwsze takich plików nie wrzucamy do miejsca gdzie jest kod javy
Po drugie nie z tego pliku aplikacja korzysta podczas działania - aplikacja korzysta z pliku znajdującego się w katalogu target.
Katalog target tworzony jest podczas wykonania przez mavena polecenia "install"

2016-10-10 15:20 UTC, rzonsol commented on src/main/java/org/elearning/portfolio/StudentDAO.java
> +    public void setDataSource(DataSource ds);
z tym nie za bardzo wiem co mam zrobić

2016-10-10 15:20 UTC, rzonsol commented on src/main/java/org/elearning/portfolio/StudentJDBCTemplate.java
> +    public void setDataSource(DataSource dataSource) {
z tym również nie wiem co za bardzo mam zrobić

2016-10-10 19:48 UTC, mszpiler requested changes

2016-10-10 19:48 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/UserDAO.java
> +    public void setDataSource(DataSource ds);
Do wywalena ta metoda

2016-10-10 19:48 UTC, mszpiler commented on src/main/java/org/elearning/portfolio/UserJDBCTemplate.java
> +        String H2 = "SELECT * FROM USERS1 ;";
Nie można tak zostawić aby było USERS1, powinno być USER

2016-10-10 20:33 UTC, mszpiler approved these changes

2016-10-10 20:36 UTC, merged