Services to message and user
rzonsol/java-portfolio pull request #7
Opened 2016-10-13 19:38 UTC by rzonsol

2016-10-13 20:47 UTC, mszpiler requested changes

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/message/MessageDAO.java
> +    public List<Message> userMessages(Integer userId);
zaczynamy od czasownika - get

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/message/MessageDAO.java
> +    public List<Message> listMessage();
lepiej getMessages

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/user/UserDAO.java
> +    public List <User> getUserData(Integer id);
Wystarczy getUser

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/user/UserDAO.java
> +    public void addRoleToUser(Integer userId, Integer roleId);
addUserRole

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/user/UserDAO.java
> +    public List<Message> userMessages(Integer userId);
getMessagesByUserId

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/user/UserDAO.java
> +    public List<User> listUsers();
getUsers

2016-10-13 20:47 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/user/UserDAO.java
> +    public List<Role> userRoles(Integer userId);
getUserRoles

2016-10-15 19:20 UTC, mszpiler requested changes

2016-10-15 19:20 UTC, mszpiler commented on first-step/pom.xml
> +                    <url>jdbc:h2:file:./first-step/target/portfolio-db/portfolio-db</url>
dwa razy /portfolio-db ??

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/First.java
> +		UserDAOImpl userDAOImple = (UserDAOImpl)context.getBean("userDAOImpl");
Po co więc implementowałeś interfejs skoro stosujesz UserDAOImpl??

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/message/MessageDAO.java
> +     * This is the method to be used to create
Dla oczywistych metod nie ma sensu pisać komentarzy

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/message/MessageDAO.java
> +    public Integer countMessages(Integer userId);
countMessages przenies do serwisu

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/services/MessageService.java
> +    private MessageDAOImpl message;
O! I tutaj jest ten karygodny błąd. MessageService jest uzależniony od implementacji MessageDAO, co jest sprzeczne zupełnie z koncepcją Dependency Injection. Tutaj powinieneś użyć interfejsu, właśnie dlatego stworzyłeś wcześniej ten interfejs - aby operować na interfejsach.

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/services/MessageService.java
> +    public MessageService(MessageDAOImpl message){
Podobnie tutaj użyj interfejsu - nie wiąż Serwisu z implementacją MessageDAOImpl

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/services/UserService.java
> +    private  UserDAOImpl user  ;
Podobnie - używaj interfejsów, implementacja jest definiowana w konfiguracji xml

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/services/UserService.java
> +    public List <User>  getUser(Integer userId){return user.getUser(userId) ;}
A to ciekawe getUser - liczba pojedyncza a zwraca listę - ta metoda jest niejasna. Skoro getUser to powinno zwrócić jeden rekord, a jeżeli wystąpi więcej, no to raczej jest błąd.

2016-10-15 19:20 UTC, mszpiler commented on first-step/src/main/java/org/elearning/portfolio/user/UserDAO.java
> +    public List <User> getUser(Integer id);
Nie lista ale jeden element. Zakładamy że dla id jest tylko jeden user.

2016-10-16 04:36 UTC, rzonsol commented on first-step/pom.xml
> +                    <url>jdbc:h2:file:./first-step/target/portfolio-db/portfolio-db</url>
pierwsze tworzy folder a drugie bazę danych, ale jak chcesz to mogę to zmienić

2016-10-16 08:18 UTC, mszpiler approved these changes

2016-10-16 13:10 UTC, merged